version: 2

jobs:
  test-job:
    environment:
      NODE_ENV: development
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            cp .env.testing .env
      - run:
          name: Deps
          command: |
            npm install
      - run:
          name: Run migrations
          command: npx adonis migration:run
      - run:
          name: Tests
          command: npm run test

workflows:
  version: 2

  test:
    jobs:
      - test-job
